"""create initial schema

Revision ID: 429362eb9277
Revises: 
Create Date: 2026-02-22 15:18:11.962063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '429362eb9277'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('roles', sa.JSON(), nullable=False),
    sa.Column('pin', sa.String(length=6), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('menu_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('json_blob', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_menu_versions_created', 'menu_versions', ['created_at'], unique=False)
    op.create_index('idx_menu_versions_user', 'menu_versions', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_menu_versions_created_by_user_id'), 'menu_versions', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_menu_versions_id'), 'menu_versions', ['id'], unique=False)
    op.create_table('table_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_label', sa.String(length=50), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('waiter_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['waiter_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_table_sessions_opened', 'table_sessions', ['opened_at'], unique=False)
    op.create_index('idx_table_sessions_waiter', 'table_sessions', ['waiter_user_id'], unique=False)
    op.create_index(op.f('ix_table_sessions_id'), 'table_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_table_sessions_opened_at'), 'table_sessions', ['opened_at'], unique=False)
    op.create_index(op.f('ix_table_sessions_waiter_user_id'), 'table_sessions', ['waiter_user_id'], unique=False)
    op.create_table('menu_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_version_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('station', sa.String(length=100), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['menu_version_id'], ['menu_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_menu_items_category', 'menu_items', ['category'], unique=False)
    op.create_index('idx_menu_items_station', 'menu_items', ['station'], unique=False)
    op.create_index(op.f('ix_menu_items_category'), 'menu_items', ['category'], unique=False)
    op.create_index(op.f('ix_menu_items_external_id'), 'menu_items', ['external_id'], unique=False)
    op.create_index(op.f('ix_menu_items_id'), 'menu_items', ['id'], unique=False)
    op.create_index(op.f('ix_menu_items_menu_version_id'), 'menu_items', ['menu_version_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_session_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['table_session_id'], ['table_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_orders_created', 'orders', ['created_at'], unique=False)
    op.create_index('idx_orders_created_by', 'orders', ['created_by_user_id'], unique=False)
    op.create_index('idx_orders_status', 'orders', ['status'], unique=False)
    op.create_index('idx_orders_table_session', 'orders', ['table_session_id'], unique=False)
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_created_by_user_id'), 'orders', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_table_session_id'), 'orders', ['table_session_id'], unique=False)
    op.create_table('nlp_training_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.String(length=500), nullable=False),
    sa.Column('predicted_menu_item_id', sa.Integer(), nullable=True),
    sa.Column('corrected_menu_item_id', sa.Integer(), nullable=True),
    sa.Column('corrected_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['corrected_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['corrected_menu_item_id'], ['menu_items.id'], ),
    sa.ForeignKeyConstraint(['predicted_menu_item_id'], ['menu_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_nlp_samples_corrected_by', 'nlp_training_samples', ['corrected_by_user_id'], unique=False)
    op.create_index('idx_nlp_samples_created', 'nlp_training_samples', ['created_at'], unique=False)
    op.create_index(op.f('ix_nlp_training_samples_corrected_by_user_id'), 'nlp_training_samples', ['corrected_by_user_id'], unique=False)
    op.create_index(op.f('ix_nlp_training_samples_id'), 'nlp_training_samples', ['id'], unique=False)
    op.create_index(op.f('ix_nlp_training_samples_predicted_menu_item_id'), 'nlp_training_samples', ['predicted_menu_item_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('line_total', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_order_items_menu_item', 'order_items', ['menu_item_id'], unique=False)
    op.create_index('idx_order_items_order', 'order_items', ['order_id'], unique=False)
    op.create_index('idx_order_items_status', 'order_items', ['status'], unique=False)
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_index(op.f('ix_order_items_menu_item_id'), 'order_items', ['menu_item_id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_table('receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('printed_at', sa.DateTime(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipts_id'), 'receipts', ['id'], unique=False)
    op.create_index(op.f('ix_receipts_order_id'), 'receipts', ['order_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receipts_order_id'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_id'), table_name='receipts')
    op.drop_table('receipts')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_menu_item_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_index('idx_order_items_status', table_name='order_items')
    op.drop_index('idx_order_items_order', table_name='order_items')
    op.drop_index('idx_order_items_menu_item', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_nlp_training_samples_predicted_menu_item_id'), table_name='nlp_training_samples')
    op.drop_index(op.f('ix_nlp_training_samples_id'), table_name='nlp_training_samples')
    op.drop_index(op.f('ix_nlp_training_samples_corrected_by_user_id'), table_name='nlp_training_samples')
    op.drop_index('idx_nlp_samples_created', table_name='nlp_training_samples')
    op.drop_index('idx_nlp_samples_corrected_by', table_name='nlp_training_samples')
    op.drop_table('nlp_training_samples')
    op.drop_index(op.f('ix_orders_table_session_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_by_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_index('idx_orders_table_session', table_name='orders')
    op.drop_index('idx_orders_status', table_name='orders')
    op.drop_index('idx_orders_created_by', table_name='orders')
    op.drop_index('idx_orders_created', table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_menu_items_menu_version_id'), table_name='menu_items')
    op.drop_index(op.f('ix_menu_items_id'), table_name='menu_items')
    op.drop_index(op.f('ix_menu_items_external_id'), table_name='menu_items')
    op.drop_index(op.f('ix_menu_items_category'), table_name='menu_items')
    op.drop_index('idx_menu_items_station', table_name='menu_items')
    op.drop_index('idx_menu_items_category', table_name='menu_items')
    op.drop_table('menu_items')
    op.drop_index(op.f('ix_table_sessions_waiter_user_id'), table_name='table_sessions')
    op.drop_index(op.f('ix_table_sessions_opened_at'), table_name='table_sessions')
    op.drop_index(op.f('ix_table_sessions_id'), table_name='table_sessions')
    op.drop_index('idx_table_sessions_waiter', table_name='table_sessions')
    op.drop_index('idx_table_sessions_opened', table_name='table_sessions')
    op.drop_table('table_sessions')
    op.drop_index(op.f('ix_menu_versions_id'), table_name='menu_versions')
    op.drop_index(op.f('ix_menu_versions_created_by_user_id'), table_name='menu_versions')
    op.drop_index('idx_menu_versions_user', table_name='menu_versions')
    op.drop_index('idx_menu_versions_created', table_name='menu_versions')
    op.drop_table('menu_versions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
