"""add is_active column to menu_items

Revision ID: 7610f4bb93c2
Revises: 429362eb9277
Create Date: 2026-02-22 16:08:32.425305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7610f4bb93c2'
down_revision = '429362eb9277'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add is_active column with default value of True (server_default for existing rows)
    op.add_column('menu_items', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_items', 'is_active')
    # ### end Alembic commands ###
