"""Add color field to workstations

Revision ID: 9cd172abe472
Revises: 3d8c9b1f2e5a
Create Date: 2026-02-24 22:39:41.231105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cd172abe472'
down_revision = '3d8c9b1f2e5a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add the color column to workstations - SQLite doesn't support ALTER COLUMN
    op.add_column('workstations', sa.Column('color', sa.String(length=7), nullable=False, server_default='#667eea'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workstations', 'color')
    # ### end Alembic commands ###
