"""add restaurant_profile table

Revision ID: a1b2c3d4e5f6
Revises: 
Create Date: 2026-02-23 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant_profiles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('restaurant_id', sa.String(length=255), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('phone', sa.String(length=20), nullable=True),
        sa.Column('address', sa.String(length=500), nullable=True),
        sa.Column('extra_details', sa.JSON(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('restaurant_id', name='uq_restaurant_profiles_restaurant_id')
    )
    op.create_index('idx_restaurant_profiles_id', 'restaurant_profiles', ['restaurant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_restaurant_profiles_id', table_name='restaurant_profiles')
    op.drop_table('restaurant_profiles')
    # ### end Alembic commands ###
